spring.application.name=api-gateway

# Server Configuration
server.port=8080

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# GATEWAY ROUTES
# Rota para o auth-user-service
spring.cloud.gateway.routes[0].id=auth-user-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**,/users/**

# Rota para o product-shop-service
# spring.cloud.gateway.routes[1].id=product-shop-service
# spring.cloud.gateway.routes[1].uri=lb://PRODUCT-SHOP-SERVICE
# spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**,/cart/**,/wishlist/**

# ===== JWT CONFIGURATION =====
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# ===== LOGGING =====
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.lslshop.gateway=DEBUG